### ISSUE TITLE
Confirmación de la tarea

### ISSUE THREAD

**Issue by JuanjoVallejo** [AFIF-UG/Introduccion_a_Python-Curso_Online#4]
Solo para confirmar que mi código(https://github.com/JuanjoVallejo/RepoTareas/blob/main/Untitled0.ipynb)
 se subió correctamente

**Comment by Edgar-La** [comment]
Es correcto, se ha subido.
Recuerda colocar tus dudas y comentarios en el Issue del día correspondinte.
También te recomendamos usar la forma [palabra] (link) para colocar vínculos.
